"""add source_score_events table

Revision ID: 80038e602672
Revises: a7129a228980
Create Date: 2026-09-28 20:13:51.628733

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80038e602672"
down_revision: str | None = "a7129a228980"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_score_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("outcome", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "claim_id", name="uq_source_score_event"),
    )
    op.create_index(
        op.f("ix_source_score_events_claim_id"), "source_score_events", ["claim_id"], unique=False
    )
    op.create_index(
        op.f("ix_source_score_events_source_id"), "source_score_events", ["source_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_source_score_events_source_id"), table_name="source_score_events")
    op.drop_index(op.f("ix_source_score_events_claim_id"), table_name="source_score_events")
    op.drop_table("source_score_events")
    # ### end Alembic commands ###
